# Generated by Django 3.2 on 2021-04-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='mail@mail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='message me', max_length=40),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='name', max_length=300),
        ),
    ]
